from __future__ import annotations
# Auto generated by torchWork.torchWork.loss_tree .
# Do not modify!
# Git ignore this!

from torchWork import LossTree

class Loss_root(LossTree):
    def __init__(self):
        super().__init__()
        self.name = 'loss_root'
        self.harmonics: float = None
        self.children = ['harmonics', ]

