#!/bin/bash

module purge
source /scratch/$USER/py_env/symmEnv/select_images
singularity exec --overlay /scratch/$USER/py_env/$ENV_NAME/$OVERLAY:ro /scratch/work/public/singularity/$SINGULARITY $(which srun) --time=1:00:00 --pty python3 ship.py $1
